services:
  recommendations:
    build: .
    container_name: recommendations
    environment:
      - ENV_VAR=example
    volumes:
      - ./app:/app
    depends_on:
      - recommendations_cache
  recommendations_cache:
    image: "redis:alpine"
    container_name: recommendations_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
